---
title: "Prometheus' Architecture Documentation"
subtitle: "Foundational Framework of the Prometheus Reasoning System"
author: "Caleb Hale"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---


## Overview
The Prometheus' Architecture is a foundational framework for a metamathematical reasoning system. It is designed to contain the expressive power of ZFC set theory while bridging the reasoning levels of rigorous mathematical logic and human-level reasoning. The architecture is built upon a set of primitives and constructions that allow for the representation and manipulation of mathematical objects and concepts.

## To Do and Future Work
### Top Priority
* Explore the "environment" concept with Claude to understand how a program might be an agent according to my perspective, and how to implement this in Prometheus.

* Finalize axioms for numbers systems, (e.g., Peano's axioms, Frege's axioms)
* Explicitly define axioms for relations (equivalence, partial order, strict partial order, etc.) and mappings, enabling checking for equal cardinality of sets (allowing the "number" abstraction to be defined as a set of equivalence classes of sets with equal cardinality?).
* Define axioms for predicates, including quantifiers and logical connectives (and, or, not, implies, etc.) and how they relate to the custom set types (constant, variable-constant, variable).
* Define incomplete extensional definitions with unknown unknowns, and how they relate to the custom set types (constant, variable-constant, variable). Note: define as an unknown that aligns with known (an unknown from the category of possibilities defined by a known detail). Only unknown unknowns with no known details are impossible to define.
* Define attributes by their relationships to other objects and their possible values, and explore abstraction with attributes and how they relate to the custom set types (constant, variable-constant, variable).
### Next Priority

* Define axioms for functions, including injective, surjective, bijective, and other properties

* Define axioms for the custom set types (constant, variable-constant, variable) and their relationships to each other and to standard set theory.


* Explore tests for determining cardinality of sets, including finite, countably infinite, and uncountably infinite sets (allowing explicit exhaustive enumeration of possibilities for sufficiently small finite sets).


## Program Structure
Mathematical objects exist (primarily as sets) within a graph structure, with relationships and operations between them. ...

## Primitives
* Sets (constant, variable-constant, and variable. The program will attempt to classify everything in terms of constant or variable sets)
  + Constant type set: {}C (represents a collection as a single object)
  + Variable-constant type set: {}VC (represents a possibility space of an unknown single object)
  + Variable type set: {}V (represents a collection of objects as an abstraction over all members of the collection)
* [^1][Rust primitives](https://claude.ai/chat/491db745-dce3-4b0c-8d09-138aeda0d09b)
    + String
    + Integer
    + Boolean
    + etc.
  + sub-item 2
    - sub-sub-item 1

[^1]: "primitive" as endpoints of reducing evaluation, but conceptually reducible. They are computationally treated as primitives, but not logically.

## Constructions and equivalencies:

### Standard set theory foundation constructions, with constant sets:
::: {}
* Intersection
: A∩B = {x | x∈A and x∈B}C
* Union
: A∪B = {x | x∈A or x∈B}C
* Power Set
: 𝒫(A) = {X | X⊆A}C
* Predicate Subset
: {x | P(x)}C = {x | x∈A and P(x)}C
* Cartesian Product
: A×B = {(a,b) | a∈A and b∈B}C
* Function Mapping
: f(A) = {f(x) | x∈A}C
:::

As well as extending set theory formulations that build up set theory constructively:
* Disjoint Union
: A⊎B = {AX{0}C ∪ BX{1}C}C
* Relation
: R⊆A×B = { (a,b) | a∈A and b∈B }C
* Function
: f:A→B = { (a,b) | a∈A and b∈B and f(a)=b }C [^2]
* etc.

[^2]: with the additional constraint that for all a∈A, there exists a unique b∈B such that (a,b)∈f; that is, one input maps to only one output

### Ambiguity and Possibility constructions, with variable-constant sets:
* Impossibility: 
: NA = {}VC 
* Tautology/Single possibility: 
: x = {x}VC
* Possibility compilation: 
: {A={...}VC, B={...}VC}VC = {AUB}VC
* Ambiguous Component:
: f({...}VC) = {f(...)}VC -- A VC set with type X members can be used as a component in any construction, object method, or operation that requires a type X member. Operation and object method results will be a VC set as a collection of evaluation outcomes for each member. E.g. {3, 4}%3 = {0,1} E.g. length({“12”, 12}) = {2, NA}


### Abstraction with variable sets:



Also, for any set that can be validly constructed as one type of set, its intension is valid for the other types of sets. E.g. {1,2,3}C ⇔ {1,2,3}VC ⇔ {1,2,3}V. 


## Starting Axioms and Template Structures:
### Axioms


### Starting Template Structures
Progression Axioms:
1. Some first object exists (e.g., 0)
2. Every object has a successor, which is also an object.
3. No two objects have the same successor
4. The first object is not the successor of any object.
5. If a property is possessed by the first object and also by the successor of every object that has that property, then it is possessed by all objects (including classifications and memberships).

This is a generalization of Peano's Axioms:
1. 0 is a number.
2. Every number has a successor, which is also a number.
3. No two numbers have the same successor
4. 0 is not the successor of any number.
5. If a property is possessed by 0 and also by the successor of every number that has that property, then it is possessed by all numbers. 
* Endless sequence of unique numbers (via 2 and 3) that don't loop (via 4), which includes all numbers (via 5).
* "Ordinal arithmetic" -- m+n is defined using m+0=m and m+(n+1)=S(m+n), reducing recursion. Defines addition and equivalents for progressions.

* Some mechanism of mapping between sets to compare their cardinality, allowing the definition of numbers as equivalence classes of sets with equal cardinality. (One-one relation identification with the two sets as domain and codomain.)
pdf pg 37

[Number as defined by collection of equivalence classes of sets with equal cardinality]

Peanos' Axioms and/or Frege's Axioms
Predicates as functions that map to truth values

## Misc Notes:
* Set-typing; indicates membership of a constant or subsetting of constant-variable or variable sets in relation to the Constant "type" set. Useful for defining allowed domains and behaviors. Adds "types" but in a more intuitive approach, allowing a term to belong to multiple types. X is of settype A means: X is a Constant as a member of A or X is either a VC set or variable set as a subset of A.

## Walkthrough and Examples


